spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/board
        username: root
        password: zxc8294
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                #        show_sql: true
                format_sql: true

logging.level:
    org.hibernate.SQL: debug
